---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: trusty64 
    driver:
      box: "ubuntu/trusty64"

suites:
  - name: default
    run_list:
      - recipe[chef-peach::default]
      - recipe[statsdaemon-bitly::default]
    attributes:
